<a href="https://colab.research.google.com/github/JimKing100/NFL-Live/blob/master/data-science/actuals/Actuals_Kicker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Imports
import pandas as pd

In [0]:
# Load the raw data
player_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/NFL-Live/master/data-science/data/raw/players.csv')
kicking_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/NFL-Live/master/data-science/data/raw/kicking.csv')
missed_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/NFL-Live/master/data-science/data/raw/missedfg.csv')
conv_df = pd.read_csv('https://raw.githubusercontent.com/JimKing100/NFL-Live/master/data-science/data/raw/conv.csv')

In [3]:
# The players dataframe - includes all the kickers for the 2019 NFL season
player_df.head()

  player          first     last                 name position1  start
0     SF  San Francisco    49ers  San Francisco 49ers        DF   2000
1    CHI        Chicago    Bears        Chicago Bears        DF   2000
2    CIN     Cincinnati  Bengals   Cincinnati Bengals        DF   2000
3    BUF        Buffalo    Bills        Buffalo Bills        DF   2000
4    DEN         Denver  Broncos       Denver Broncos        DF   2000

In [4]:
# The kicking dataframe - raw kicking data for all 2019 kickers for seasons 2000-2019
kicking_df.head()

   uid  gid   player   del first       last  ... fgl  fp  game  seas  year  team
0   15    8  AV-0400  KEEP  Adam  Vinatieri  ...   0   4     1     5  2000    NE
1   59   30  AV-0400  KEEP  Adam  Vinatieri  ...   0  13     2     5  2000    NE
2   76   38  AV-0400  KEEP  Adam  Vinatieri  ...   0   1     3     5  2000    NE
3  100   51  AV-0400  KEEP  Adam  Vinatieri  ...   0   4     4     5  2000    NE
4  122   63  AV-0400  KEEP  Adam  Vinatieri  ...   0   4     5     5  2000    NE

[5 rows x 17 columns]

In [5]:
# The missed field goal dataframe - raw missed field goal data for all 2019 kickers for seasons 2000-2019
missed_df.head()

    pid  gid  year  week fgxp  ... first       last            name dist  good
0   517    4  2000     1   FG  ...  John       Hall       John Hall   52     0
1   583    4  2000     1   FG  ...  John       Hall       John Hall   48     0
2   877    6  2000     1   FG  ...  Kris    Heppner    Kris Heppner   52     0
3  1203    8  2000     1   FG  ...  Adam  Vinatieri  Adam Vinatieri   55     0
4  1435    9  2000     1   FG  ...  Doug      Brien      Doug Brien   52     0

[5 rows x 11 columns]

In [6]:
# The two point conversion dataframe - raw data for all two point conversions
conv_df.head()

    pid  gid  year  week  type  ...      trg first_trg last_trg       name_trg conv
0   456    3  2000     1  PASS  ...  RI-0200    Raghib   Ismail  Raghib Ismail    1
1  1408    9  2000     1  RUSH  ...      NaN       NaN      NaN            NaN    1
2  2528   16  2000     2  PASS  ...  BC-1600       Ben   Coates     Ben Coates    1
3  2779   17  2000     2  PASS  ...  TD-0800    Tyrone    Davis   Tyrone Davis    1
4  3052   19  2000     2  RUSH  ...      NaN       NaN      NaN            NaN    1

[5 rows x 18 columns]

In [0]:
# Pull the stats to calculate the kicker points - the fp column is the points total for each game
def pull_stats(df, df1, df2, df3, col, p, y, g):
    missedfg_points = 0
    conversion_points = 0
    if (df[col].loc[(df['player']==p) & (df['year']==y) & (df['game']==g)].empty):
        start_year = df1['start'].loc[(df1['player']==p)].iloc[0]
        if y < start_year:
            points = float('NaN')
        else:
            points = 0
    else:
        conversion_points1 = df3['conv'].loc[(df3['bc']==p) & (df3['year']==y) & (df3['week']==g)].count()
        conversion_points2 = df3['conv'].loc[(df3['psr']==p) & (df3['year']==y) & (df3['week']==g)].count()
        conversion_points3 = df3['conv'].loc[(df3['trg']==p) & (df3['year']==y) & (df3['week']==g)].count()

        conversion_points = conversion_points1 + conversion_points2 + conversion_points3
        missedfg_points = df2['good'].loc[(df2['fkicker']==p) & (df2['year']==y) & (df2['week']==g)].count()
        points = df[col].loc[(df['player']==p) & (df['year']==y) & (df['game']==g)].iloc[0]

    return points - missedfg_points + conversion_points

In [0]:
# Add a row to the final_df dataframe
# Each row represents the actual kicking points for each game for each kicker
def add_row(df, p, f, l, n, pos, value_list):

    df = df.append({'player': p,
                    'first': f,
                    'last': l,
                    'name': n,
                    'position1': pos,
                    '2000-game1': value_list[0], 
                    '2000-game2': value_list[1],
                    '2000-game3': value_list[2], 
                    '2000-game4': value_list[3], 
                    '2000-game5': value_list[4], 
                    '2000-game6': value_list[5], 
                    '2000-game7': value_list[6], 
                    '2000-game8': value_list[7], 
                    '2000-game9': value_list[8],
                    '2000-game10': value_list[9],
                    '2000-game11': value_list[10],
                    '2000-game12': value_list[11],
                    '2000-game13': value_list[12],
                    '2000-game14': value_list[13],
                    '2000-game15': value_list[14],
                    '2000-game16': value_list[15],
                    '2001-game1': value_list[16], 
                    '2001-game2': value_list[17],
                    '2001-game3': value_list[18], 
                    '2001-game4': value_list[19], 
                    '2001-game5': value_list[20], 
                    '2001-game6': value_list[21], 
                    '2001-game7': value_list[22], 
                    '2001-game8': value_list[23], 
                    '2001-game9': value_list[24],
                    '2001-game10': value_list[25],
                    '2001-game11': value_list[26],
                    '2001-game12': value_list[27],
                    '2001-game13': value_list[28],
                    '2001-game14': value_list[29],
                    '2001-game15': value_list[30],
                    '2001-game16': value_list[31],
                    '2002-game1': value_list[32], 
                    '2002-game2': value_list[33],
                    '2002-game3': value_list[34], 
                    '2002-game4': value_list[35], 
                    '2002-game5': value_list[36], 
                    '2002-game6': value_list[37], 
                    '2002-game7': value_list[38], 
                    '2002-game8': value_list[39], 
                    '2002-game9': value_list[40],
                    '2002-game10': value_list[41],
                    '2002-game11': value_list[42],
                    '2002-game12': value_list[43],
                    '2002-game13': value_list[44],
                    '2002-game14': value_list[45],
                    '2002-game15': value_list[46],
                    '2002-game16': value_list[47],
                    '2003-game1': value_list[48], 
                    '2003-game2': value_list[49],
                    '2003-game3': value_list[50], 
                    '2003-game4': value_list[51], 
                    '2003-game5': value_list[52], 
                    '2003-game6': value_list[53], 
                    '2003-game7': value_list[54], 
                    '2003-game8': value_list[55], 
                    '2003-game9': value_list[56],
                    '2003-game10': value_list[57],
                    '2003-game11': value_list[58],
                    '2003-game12': value_list[59],
                    '2003-game13': value_list[60],
                    '2003-game14': value_list[61],
                    '2003-game15': value_list[62],
                    '2003-game16': value_list[63],
                    '2004-game1': value_list[64], 
                    '2004-game2': value_list[65],
                    '2004-game3': value_list[66], 
                    '2004-game4': value_list[67], 
                    '2004-game5': value_list[68], 
                    '2004-game6': value_list[69], 
                    '2004-game7': value_list[70], 
                    '2004-game8': value_list[71], 
                    '2004-game9': value_list[72],
                    '2004-game10': value_list[73],
                    '2004-game11': value_list[74],
                    '2004-game12': value_list[75],
                    '2004-game13': value_list[76],
                    '2004-game14': value_list[77],
                    '2004-game15': value_list[78],
                    '2004-game16': value_list[79],
                    '2005-game1': value_list[80], 
                    '2005-game2': value_list[81],
                    '2005-game3': value_list[82], 
                    '2005-game4': value_list[83], 
                    '2005-game5': value_list[84], 
                    '2005-game6': value_list[85], 
                    '2005-game7': value_list[86], 
                    '2005-game8': value_list[87], 
                    '2005-game9': value_list[88],
                    '2005-game10': value_list[89],
                    '2005-game11': value_list[90],
                    '2005-game12': value_list[91],
                    '2005-game13': value_list[92],
                    '2005-game14': value_list[93],
                    '2005-game15': value_list[94],
                    '2005-game16': value_list[95],
                    '2006-game1': value_list[96], 
                    '2006-game2': value_list[97],
                    '2006-game3': value_list[98], 
                    '2006-game4': value_list[99], 
                    '2006-game5': value_list[100], 
                    '2006-game6': value_list[101], 
                    '2006-game7': value_list[102], 
                    '2006-game8': value_list[103], 
                    '2006-game9': value_list[104],
                    '2006-game10': value_list[105],
                    '2006-game11': value_list[106],
                    '2006-game12': value_list[107],
                    '2006-game13': value_list[108],
                    '2006-game14': value_list[109],
                    '2006-game15': value_list[110],
                    '2006-game16': value_list[111],
                    '2007-game1': value_list[112], 
                    '2007-game2': value_list[113],
                    '2007-game3': value_list[114], 
                    '2007-game4': value_list[115], 
                    '2007-game5': value_list[116], 
                    '2007-game6': value_list[117], 
                    '2007-game7': value_list[118], 
                    '2007-game8': value_list[119], 
                    '2007-game9': value_list[120],
                    '2007-game10': value_list[121],
                    '2007-game11': value_list[122],
                    '2007-game12': value_list[123],
                    '2007-game13': value_list[124],
                    '2007-game14': value_list[125],
                    '2007-game15': value_list[126],
                    '2007-game16': value_list[127],
                    '2008-game1': value_list[128], 
                    '2008-game2': value_list[129],
                    '2008-game3': value_list[130], 
                    '2008-game4': value_list[131], 
                    '2008-game5': value_list[132], 
                    '2008-game6': value_list[133], 
                    '2008-game7': value_list[134], 
                    '2008-game8': value_list[135], 
                    '2008-game9': value_list[136],
                    '2008-game10': value_list[137],
                    '2008-game11': value_list[138],
                    '2008-game12': value_list[139],
                    '2008-game13': value_list[140],
                    '2008-game14': value_list[141],
                    '2008-game15': value_list[142],
                    '2008-game16': value_list[143],
                    '2009-game1': value_list[144], 
                    '2009-game2': value_list[145],
                    '2009-game3': value_list[146], 
                    '2009-game4': value_list[147], 
                    '2009-game5': value_list[148], 
                    '2009-game6': value_list[149], 
                    '2009-game7': value_list[150], 
                    '2009-game8': value_list[151], 
                    '2009-game9': value_list[152],
                    '2009-game10': value_list[153],
                    '2009-game11': value_list[154],
                    '2009-game12': value_list[155],
                    '2009-game13': value_list[156],
                    '2009-game14': value_list[157],
                    '2009-game15': value_list[158],
                    '2009-game16': value_list[159],
                    '2010-game1': value_list[160], 
                    '2010-game2': value_list[161],
                    '2010-game3': value_list[162], 
                    '2010-game4': value_list[163], 
                    '2010-game5': value_list[164], 
                    '2010-game6': value_list[165], 
                    '2010-game7': value_list[166], 
                    '2010-game8': value_list[167], 
                    '2010-game9': value_list[168],
                    '2010-game10': value_list[169],
                    '2010-game11': value_list[170],
                    '2010-game12': value_list[171],
                    '2010-game13': value_list[172],
                    '2010-game14': value_list[173],
                    '2010-game15': value_list[174],
                    '2010-game16': value_list[175],
                    '2011-game1': value_list[176], 
                    '2011-game2': value_list[177],
                    '2011-game3': value_list[178], 
                    '2011-game4': value_list[179], 
                    '2011-game5': value_list[180], 
                    '2011-game6': value_list[181], 
                    '2011-game7': value_list[182], 
                    '2011-game8': value_list[183], 
                    '2011-game9': value_list[184],
                    '2011-game10': value_list[185],
                    '2011-game11': value_list[186],
                    '2011-game12': value_list[187],
                    '2011-game13': value_list[188],
                    '2011-game14': value_list[189],
                    '2011-game15': value_list[190],
                    '2011-game16': value_list[191],
                    '2012-game1': value_list[192], 
                    '2012-game2': value_list[193],
                    '2012-game3': value_list[194], 
                    '2012-game4': value_list[195], 
                    '2012-game5': value_list[196], 
                    '2012-game6': value_list[197], 
                    '2012-game7': value_list[198], 
                    '2012-game8': value_list[199], 
                    '2012-game9': value_list[200],
                    '2012-game10': value_list[201],
                    '2012-game11': value_list[202],
                    '2012-game12': value_list[203],
                    '2012-game13': value_list[204],
                    '2012-game14': value_list[205],
                    '2012-game15': value_list[206],
                    '2012-game16': value_list[207],
                    '2013-game1': value_list[208], 
                    '2013-game2': value_list[209],
                    '2013-game3': value_list[210], 
                    '2013-game4': value_list[211], 
                    '2013-game5': value_list[212], 
                    '2013-game6': value_list[213], 
                    '2013-game7': value_list[214], 
                    '2013-game8': value_list[215], 
                    '2013-game9': value_list[216],
                    '2013-game10': value_list[217],
                    '2013-game11': value_list[218],
                    '2013-game12': value_list[219],
                    '2013-game13': value_list[220],
                    '2013-game14': value_list[221],
                    '2013-game15': value_list[222],
                    '2013-game16': value_list[223],
                    '2014-game1': value_list[224], 
                    '2014-game2': value_list[225],
                    '2014-game3': value_list[226], 
                    '2014-game4': value_list[227], 
                    '2014-game5': value_list[228], 
                    '2014-game6': value_list[229], 
                    '2014-game7': value_list[230], 
                    '2014-game8': value_list[231], 
                    '2014-game9': value_list[232],
                    '2014-game10': value_list[233],
                    '2014-game11': value_list[234],
                    '2014-game12': value_list[235],
                    '2014-game13': value_list[236],
                    '2014-game14': value_list[237],
                    '2014-game15': value_list[238],
                    '2014-game16': value_list[239],
                    '2015-game1': value_list[240], 
                    '2015-game2': value_list[241],
                    '2015-game3': value_list[242], 
                    '2015-game4': value_list[243], 
                    '2015-game5': value_list[244], 
                    '2015-game6': value_list[245], 
                    '2015-game7': value_list[246], 
                    '2015-game8': value_list[247], 
                    '2015-game9': value_list[248],
                    '2015-game10': value_list[249],
                    '2015-game11': value_list[250],
                    '2015-game12': value_list[251],
                    '2015-game13': value_list[252],
                    '2015-game14': value_list[253],
                    '2015-game15': value_list[254],
                    '2015-game16': value_list[255],
                    '2016-game1': value_list[256], 
                    '2016-game2': value_list[257],
                    '2016-game3': value_list[258], 
                    '2016-game4': value_list[259], 
                    '2016-game5': value_list[260], 
                    '2016-game6': value_list[261], 
                    '2016-game7': value_list[262], 
                    '2016-game8': value_list[263], 
                    '2016-game9': value_list[264],
                    '2016-game10': value_list[265],
                    '2016-game11': value_list[266],
                    '2016-game12': value_list[267],
                    '2016-game13': value_list[268],
                    '2016-game14': value_list[269],
                    '2016-game15': value_list[270],
                    '2016-game16': value_list[271],
                    '2017-game1': value_list[272], 
                    '2017-game2': value_list[273],
                    '2017-game3': value_list[274], 
                    '2017-game4': value_list[275], 
                    '2017-game5': value_list[276], 
                    '2017-game6': value_list[277], 
                    '2017-game7': value_list[278], 
                    '2017-game8': value_list[279], 
                    '2017-game9': value_list[280],
                    '2017-game10': value_list[281],
                    '2017-game11': value_list[282],
                    '2017-game12': value_list[283],
                    '2017-game13': value_list[284],
                    '2017-game14': value_list[285],
                    '2017-game15': value_list[286],
                    '2017-game16': value_list[287],
                    '2018-game1': value_list[288], 
                    '2018-game2': value_list[289],
                    '2018-game3': value_list[290], 
                    '2018-game4': value_list[291], 
                    '2018-game5': value_list[292], 
                    '2018-game6': value_list[293], 
                    '2018-game7': value_list[294], 
                    '2018-game8': value_list[295], 
                    '2018-game9': value_list[296],
                    '2018-game10': value_list[297],
                    '2018-game11': value_list[298],
                    '2018-game12': value_list[299],
                    '2018-game13': value_list[300],
                    '2018-game14': value_list[301],
                    '2018-game15': value_list[302],
                    '2018-game16': value_list[303],
                    '2019-game1': value_list[304], 
                    '2019-game2': value_list[305],
                    '2019-game3': value_list[306], 
                    '2019-game4': value_list[307], 
                    '2019-game5': value_list[308], 
                    '2019-game6': value_list[309], 
                    '2019-game7': value_list[310], 
                    '2019-game8': value_list[311], 
                    '2019-game9': value_list[312],
                    '2019-game10': value_list[313],
                    '2019-game11': value_list[314],
                    '2019-game12': value_list[315],
                    '2019-game13': value_list[316],
                    '2019-game14': value_list[317],
                    '2019-game15': value_list[318],
                    '2019-game16': value_list[319]
                     }, ignore_index=True)
    
    return df

In [0]:
# The main code for iterating through the kicker list, calculating the points and adding the rows
# to the final_df dataframe.
column_names = ['player',
                'first',
                'last',
                'name',
                'position1', 
                '2000-game1',
                '2000-game2',
                '2000-game3', 
                '2000-game4', 
                '2000-game5', 
                '2000-game6', 
                '2000-game7', 
                '2000-game8', 
                '2000-game9',
                '2000-game10',
                '2000-game11',
                '2000-game12',
                '2000-game13',
                '2000-game14',
                '2000-game15',
                '2000-game16',
                '2001-game1', 
                '2001-game2',
                '2001-game3', 
                '2001-game4', 
                '2001-game5', 
                '2001-game6', 
                '2001-game7', 
                '2001-game8', 
                '2001-game9',
                '2001-game10',
                '2001-game11',
                '2001-game12',
                '2001-game13',
                '2001-game14',
                '2001-game15',
                '2001-game16',
                '2002-game1',
                '2002-game2',
                '2002-game3', 
                '2002-game4', 
                '2002-game5', 
                '2002-game6', 
                '2002-game7', 
                '2002-game8', 
                '2002-game9',
                '2002-game10',
                '2002-game11',
                '2002-game12',
                '2002-game13',
                '2002-game14',
                '2002-game15',
                '2002-game16',
                '2003-game1', 
                '2003-game2',
                '2003-game3', 
                '2003-game4', 
                '2003-game5', 
                '2003-game6', 
                '2003-game7', 
                '2003-game8', 
                '2003-game9',
                '2003-game10',
                '2003-game11',
                '2003-game12',
                '2003-game13',
                '2003-game14',
                '2003-game15',
                '2003-game16',
                '2004-game1',
                '2004-game2',
                '2004-game3', 
                '2004-game4', 
                '2004-game5', 
                '2004-game6', 
                '2004-game7', 
                '2004-game8', 
                '2004-game9',
                '2004-game10',
                '2004-game11',
                '2004-game12',
                '2004-game13',
                '2004-game14',
                '2004-game15',
                '2004-game16',
                '2005-game1', 
                '2005-game2',
                '2005-game3', 
                '2005-game4', 
                '2005-game5', 
                '2005-game6', 
                '2005-game7', 
                '2005-game8', 
                '2005-game9',
                '2005-game10',
                '2005-game11',
                '2005-game12',
                '2005-game13',
                '2005-game14',
                '2005-game15',
                '2005-game16',
                '2006-game1',
                '2006-game2',
                '2006-game3', 
                '2006-game4', 
                '2006-game5', 
                '2006-game6', 
                '2006-game7', 
                '2006-game8', 
                '2006-game9',
                '2006-game10',
                '2006-game11',
                '2006-game12',
                '2006-game13',
                '2006-game14',
                '2006-game15',
                '2006-game16',
                '2007-game1', 
                '2007-game2',
                '2007-game3', 
                '2007-game4', 
                '2007-game5', 
                '2007-game6', 
                '2007-game7', 
                '2007-game8', 
                '2007-game9',
                '2007-game10',
                '2007-game11',
                '2007-game12',
                '2007-game13',
                '2007-game14',
                '2007-game15',
                '2007-game16',
                '2008-game1',
                '2008-game2',
                '2008-game3', 
                '2008-game4', 
                '2008-game5', 
                '2008-game6', 
                '2008-game7', 
                '2008-game8', 
                '2008-game9',
                '2008-game10',
                '2008-game11',
                '2008-game12',
                '2008-game13',
                '2008-game14',
                '2008-game15',
                '2008-game16',
                '2009-game1', 
                '2009-game2',
                '2009-game3', 
                '2009-game4', 
                '2009-game5', 
                '2009-game6', 
                '2009-game7', 
                '2009-game8', 
                '2009-game9',
                '2009-game10',
                '2009-game11',
                '2009-game12',
                '2009-game13',
                '2009-game14',
                '2009-game15',
                '2009-game16',
                '2010-game1',
                '2010-game2',
                '2010-game3', 
                '2010-game4', 
                '2010-game5', 
                '2010-game6', 
                '2010-game7', 
                '2010-game8', 
                '2010-game9',
                '2010-game10',
                '2010-game11',
                '2010-game12',
                '2010-game13',
                '2010-game14',
                '2010-game15',
                '2010-game16',
                '2011-game1', 
                '2011-game2',
                '2011-game3', 
                '2011-game4', 
                '2011-game5', 
                '2011-game6', 
                '2011-game7', 
                '2011-game8', 
                '2011-game9',
                '2011-game10',
                '2011-game11',
                '2011-game12',
                '2011-game13',
                '2011-game14',
                '2011-game15',
                '2011-game16',
                '2012-game1',
                '2012-game2',
                '2012-game3', 
                '2012-game4', 
                '2012-game5', 
                '2012-game6', 
                '2012-game7', 
                '2012-game8', 
                '2012-game9',
                '2012-game10',
                '2012-game11',
                '2012-game12',
                '2012-game13',
                '2012-game14',
                '2012-game15',
                '2012-game16',
                '2013-game1', 
                '2013-game2',
                '2013-game3', 
                '2013-game4', 
                '2013-game5', 
                '2013-game6', 
                '2013-game7', 
                '2013-game8', 
                '2013-game9',
                '2013-game10',
                '2013-game11',
                '2013-game12',
                '2013-game13',
                '2013-game14',
                '2013-game15',
                '2013-game16',
                '2014-game1',
                '2014-game2',
                '2014-game3', 
                '2014-game4', 
                '2014-game5', 
                '2014-game6', 
                '2014-game7', 
                '2014-game8', 
                '2014-game9',
                '2014-game10',
                '2014-game11',
                '2014-game12',
                '2014-game13',
                '2014-game14',
                '2014-game15',
                '2014-game16',
                '2015-game1', 
                '2015-game2',
                '2015-game3', 
                '2015-game4', 
                '2015-game5', 
                '2015-game6', 
                '2015-game7', 
                '2015-game8', 
                '2015-game9',
                '2015-game10',
                '2015-game11',
                '2015-game12',
                '2015-game13',
                '2015-game14',
                '2015-game15',
                '2015-game16',
                '2016-game1',
                '2016-game2',
                '2016-game3', 
                '2016-game4', 
                '2016-game5', 
                '2016-game6', 
                '2016-game7', 
                '2016-game8', 
                '2016-game9',
                '2016-game10',
                '2016-game11',
                '2016-game12',
                '2016-game13',
                '2016-game14',
                '2016-game15',
                '2016-game16',
                '2017-game1', 
                '2017-game2',
                '2017-game3', 
                '2017-game4', 
                '2017-game5', 
                '2017-game6', 
                '2017-game7', 
                '2017-game8', 
                '2017-game9',
                '2017-game10',
                '2017-game11',
                '2017-game12',
                '2017-game13',
                '2017-game14',
                '2017-game15',
                '2017-game16',
                '2018-game1',
                '2018-game2',
                '2018-game3', 
                '2018-game4', 
                '2018-game5', 
                '2018-game6', 
                '2018-game7', 
                '2018-game8', 
                '2018-game9',
                '2018-game10',
                '2018-game11',
                '2018-game12',
                '2018-game13',
                '2018-game14',
                '2018-game15',
                '2018-game16',
                '2019-game1',
                '2019-game2',
                '2019-game3', 
                '2019-game4', 
                '2019-game5', 
                '2019-game6', 
                '2019-game7', 
                '2019-game8', 
                '2019-game9',
                '2019-game10',
                '2019-game11',
                '2019-game12',
                '2019-game13',
                '2019-game14',
                '2019-game15',
                '2019-game16'
                 ]

kickers_df = player_df.loc[player_df['position1'] == 'K']
player_list = kickers_df['player'].tolist()

final_df = pd.DataFrame(columns = column_names)

for player in player_list:

    first = player_df['first'].loc[(player_df['player']==player)].iloc[0]
    last = player_df['last'].loc[(player_df['player']==player)].iloc[0]
    name = player_df['name'].loc[(player_df['player']==player)].iloc[0]
    position1 = player_df['position1'].loc[(player_df['player']==player)].iloc[0]

    player_scores = []

    for year in range(2000,2020):
        for game in range(1,17):
            score = pull_stats(kicking_df, player_df, missed_df, conv_df, 'fp', player, year, game)

            player_scores.append(score)

    final_df = add_row(final_df, player, first, last, name, position1, player_scores)

In [10]:
final_df.head(50)

     player     first        last  ... 2019-game14 2019-game15 2019-game16
0   MB-0020   Michael     Badgley  ...           0           0           0
1   DB-0200       Dan      Bailey  ...           4          13           9
2   CB-2275     Chris     Boswell  ...           5           5           4
3   MB-4600      Matt      Bryant  ...           0           0           0
4   RB-4650     Randy     Bullock  ...           8           9          11
5   HB-0500  Harrison      Butker  ...          10          10           8
6   DC-0450    Daniel     Carlson  ...          10           6           9
7   MC-3000     Mason      Crosby  ...          10          12           4
8   JE-0250      Jake     Elliott  ...           6           5          10
9   KF-0075    Ka'imi   Fairbairn  ...           6          11           2
10  SF-0050       Sam      Ficken  ...           8           0           0
11  NF-0300      Nick        Folk  ...           0           0           0
12  KF-0250       Kai     Forbath  ...           0           0           0
13  MG-0306      Matt         Gay  ...           9          10           1
14  ZG-0050      Zane    Gonzalez  ...           8          10           5
15  SG-0800   Stephen  Gostkowski  ...           0           0           0
16  RG-1500    Robbie       Gould  ...           9          16           9
17  SH-0400   Stephen    Hauschka  ...           5           5           6
18  DH-3970    Dustin     Hopkins  ...          12           5          11
19  GJ-1200      Greg      Joseph  ...           0           0           0
20  YK-0100  Younghoe         Koo  ...           0           0           0
21  JL-0207      Josh       Lambo  ...           9           7          16
22  TL-1062        Ty        Long  ...           0           0           0
23  WL-0300       Wil        Lutz  ...          10           9           6
24  BM-0062     Brett       Maher  ...           0           0           0
25  CM-2137     Chase  McLaughlin  ...           0           0           0
26  BM-1650   Brandon     McManus  ...           3           9          14
27  JM-7000     Jason       Myers  ...           6           9           3
28  MN-0800      Mike      Nugent  ...           0           0           0
29  CP-0575      Cody      Parkey  ...           0           0           0
30  EP-0512      Eddy     Pineiro  ...           7           4          13
31  MP-2100      Matt      Prater  ...           5           5          11
32  AR-1450   Aldrick       Rosas  ...           4           5           4
33  JS-0350     Jason     Sanders  ...           7           8           0
34  CS-0250     Cairo      Santos  ...           0           0           0
35  AS-0575    Austin     Seibert  ...           7           3           6
36  JS-3825      Joey        Slye  ...           8           8           4
37  RS-3400      Ryan      Succop  ...           0           0           0
38  JT-3950    Justin      Tucker  ...           4           7          17
39  KV-0250     Kaare      Vedvik  ...           0           0           0
40  AV-0400      Adam   Vinatieri  ...           0           0           0
41  GZ-2000      Greg    Zuerlein  ...           0           9           7

[42 rows x 325 columns]

In [0]:
# Save the results to .csv file
final_df.to_csv('/content/actuals_kickers.csv', index=False)